_wandb:
    value:
        cli_version: 0.23.1
        e:
            8nb7cetbiua79n3ukgbymwk7ape4dt9v:
                codePath: notebooks/logistic_regression.ipynb
                cpu_count: 12
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1021821579264"
                        used: "306672177152"
                email: pierre.emery@umontreal.ca
                executable: C:\Users\pierr\miniconda3\python.exe
                git:
                    commit: f67d930b2a809901c26dec621d2e0475a1d70ab9
                    remote: https://github.com/Stephanope/Project-Hockey.git
                host: ValentinoLenovo
                memory:
                    total: "16908148736"
                os: Windows-11-10.0.26200-SP0
                program: notebooks/logistic_regression.ipynb
                python: CPython 3.13.11
                root: C:\Users\pierr\Documents\GitHub\Projet Hockey Stephano\Project-Hockey\notebooks
                startedAt: "2026-01-06T03:32:37.518730Z"
                writerId: 8nb7cetbiua79n3ukgbymwk7ape4dt9v
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
            "4": 3.13.11
            "5": 0.23.1
            "8":
                - 1
                - 3
            "12": 0.23.1
            "13": windows-amd64
features_angle:
    value:
        - shotAngle
features_distance:
    value:
        - shotDistance
features_distance_angle:
    value:
        - shotDistance
        - shotAngle
model_type:
    value: LogisticRegression(default)
notes:
    value: 'Baseline models for xG: Distance, Angle, Distance+Angle'
split_seed:
    value: 42
val_size:
    value: 0.2
